---
sidebar: sidebar 
permalink: legal-notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr. 
---
= Rechtliche Hinweise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr.



== Urheberrecht

http://www.netapp.com/us/legal/copyright.aspx[]



== Marken

NetApp, das NETAPP Logo und die auf der NetApp Markenseite aufgeführten Marken sind Marken von NetApp Inc. Andere Firmen- und Produktnamen können Marken der jeweiligen Eigentümer sein.

http://www.netapp.com/us/legal/netapptmlist.aspx[]



== Patente

Eine aktuelle Liste der NetApp Patente finden Sie unter:

https://www.netapp.com/us/media/patents-page.pdf[]



== Datenschutzrichtlinie

https://www.netapp.com/us/legal/privacypolicy/index.aspx[]



== Open Source

In den Benachrichtigungsdateien finden Sie Informationen zu Urheberrechten und Lizenzen von Drittanbietern, die in der NetApp Software verwendet werden.

* link:media/notice-aws.pdf["Hinweis für den Cloud Volumes ONTAP 9.11.1 Mediator in AWS"^]
* link:media/notice-google-cloud.pdf["Hinweis für den Cloud Volumes ONTAP 9.11.1 Mediator in Google Cloud"^]
* https://docs.netapp.com/us-en/ontap/reference_legal_notices.html#open-source["Hinweis für ONTAP"^]

