---
settings:
  name: Cloud Volumes ONTAP release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - version-number: 9.14.1
    url: "/cloud-volumes-ontap-relnotes"
  - version-number: 9.14.0
    url: "/cloud-volumes-ontap-9140-relnotes"
  - version-number: 9.13.1
    url: "/cloud-volumes-ontap-9131-relnotes"
  - version-number: 9.13.0
    url: "/cloud-volumes-ontap-9130-relnotes"
  - version-number: 9.12.1
    url: "/cloud-volumes-ontap-9121-relnotes"
  - version-number: 9.12.0
    url: "/cloud-volumes-ontap-9120-relnotes"
  - version-number: 9.11.1
    url: "/cloud-volumes-ontap-9111-relnotes"
  - version-number: 9.11.0
    url: "/cloud-volumes-ontap-9110-relnotes"
  - version-number: 9.10.1
    url: "/cloud-volumes-ontap-9101-relnotes"
  - version-number: 9.10.0
    url: "/cloud-volumes-ontap-9100-relnotes"
  - version-number: 9.9.1
    url: "/cloud-volumes-ontap-991-relnotes"
  - version-number: 9.9.0
    url: "/cloud-volumes-ontap-990-relnotes"
  - version-number: '9.8'
    url: "/cloud-volumes-ontap-98-relnotes"
  - version-number: '9.7'
    url: "/cloud-volumes-ontap-97-relnotes"
  - version-number: '9.6'
    url: "/cloud-volumes-ontap-96-relnotes"
  - version-number: '9.5'
    url: "/cloud-volumes-ontap-95-relnotes"
  - version-number: '9.4'
    url: "/cloud-volumes-ontap-94-relnotes"
  - version-number: '9.3'
    url: "/cloud-volumes-ontap-93-relnotes"
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Versionshinweise zu Hause
    url: "/index.html"
  - title: Was ist neu
    url: "/reference-new.html"
  - title: Übersicht über die Lizenzierung
    url: "/concept-licensing.html"
  - title: Unterstützte Konfigurationen
    entries:
    - title: AWS
      url: "/reference-configs-aws.html"
    - title: Azure
      url: "/reference-configs-azure.html"
    - title: Google Cloud
      url: "/reference-configs-gcp.html"
  - title: Storage-Beschränkungen
    entries:
    - title: AWS
      url: "/reference-limits-aws.html"
    - title: Azure
      url: "/reference-limits-azure.html"
    - title: Google Cloud
      url: "/reference-limits-gcp.html"
  - title: Bekannte Probleme
    url: "/reference-issues.html"
  - title: Bekannte Einschränkungen
    entries:
    - title: Allgemeine Einschränkungen
      url: "/reference-limitations.html"
    - title: Einschränkungen in AWS
      url: "/reference-limitations-aws.html"
    - title: Einschränkungen in Azure
      url: "/reference-limitations-azure.html"
    - title: Beschränkungen in Google Cloud
      url: "/reference-limitations-gcp.html"
  - title: Integration von Cloud-Providern
    url: "/reference-provider-integrations.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Was ist neu
      url: reference-new.html
    - title: Übersicht über die Lizenzierung
      url: concept-licensing.html
  - title: Amazon Web Services
    links:
    - title: Unterstützte Konfigurationen
      url: reference-configs-aws.html
    - title: Storage-Beschränkungen
      url: reference-limits-aws.html
    - title: Einschränkungen
      url: reference-limitations-aws.html
  - title: Google Cloud
    links:
    - title: Unterstützte Konfigurationen
      url: reference-configs-gcp.html
    - title: Storage-Beschränkungen
      url: reference-limits-gcp.html
    - title: Einschränkungen
      url: reference-limitations-gcp.html
  - title: Microsoft Azure
    links:
    - title: Unterstützte Konfigurationen
      url: reference-configs-azure.html
    - title: Storage-Beschränkungen
      url: reference-limits-azure.html
    - title: Einschränkungen
      url: reference-limitations-azure.html
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP-Blog
      url: https://cloud.netapp.com/blog
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
