---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Bekannte Einschränkungen für Cloud Volumes ONTAP bei allen Cloud-Providern
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Plattformen, Geräte oder Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit dem Produkt zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.

Die folgenden Einschränkungen gelten für Cloud Volumes ONTAP bei allen Cloud-Providern: AWS, Azure und Google Cloud.



== Nicht unterstützte ONTAP-Funktionen

Die folgenden Funktionen werden mit Cloud Volumes ONTAP nicht unterstützt:

* Inline-Deduplizierung auf Aggregatebene
* Deduplizierung auf Aggregatebene im Hintergrund
* Disk Maintenance Center
* Festplattenbereinigung
* FabricPool Mirroring
* Fibre Channel (FC)
* Flash Pools
* Unbegrenzte Volumes
* Interface Groups
* LIF-Failover bei Intranode
* MetroCluster
* Überprüfung durch mehrere Administratoren
+
Wenn Sie die Multi-Admin-Verifizierung auf Cloud Volumes ONTAP aktivieren, wird die Konfiguration nicht unterstützt.

* RAID4, RAID-DP, RAID-TEC (RAID0 WIRD UNTERSTÜTZT)
* Service Processor
* SnapLock Compliance und Enterprise Mode (nur Cloud WORM wird unterstützt)
* SnapMirror Synchronous
* VLANs
* Kontinuierliche Verfügbarkeit (CA) für SMB
+
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Ständig verfügbare SMB-Freigaben"^] für unterbrechungsfreie Vorgänge werden nicht unterstützt.





== Maximal gleichzeitige Replizierungsvorgänge

Die maximale Anzahl gleichzeitiger SnapMirror oder SnapVault Transfers für Cloud Volumes ONTAP beträgt 100 pro Node, unabhängig vom Instanztyp oder Machine-Typ.



== Snapshots von Cloud-Providern dürfen für Ihre Backup- und Recovery-Pläne nicht verwendet werden

Die Snapshots Ihres Cloud-Providers sollten nicht als Teil Ihres Backup- und Recovery-Plans für Cloud Volumes ONTAP Daten verwendet werden. Um die auf Cloud Volumes ONTAP gehosteten Daten zu sichern und wiederherzustellen, sollten Sie immer ONTAP Snapshot Kopien oder Backup-Lösungen von Drittanbietern verwenden.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-backup-to-cloud.html["Erfahren Sie, wie Sie NetApp Backup and Recovery zum Sichern und Wiederherstellen von ONTAP Daten verwenden"^] .


NOTE: Die ONTAP-Konsistenzpunkte im WAFL-Dateisystem bestimmen die Datenkonsistenz. Nur ONTAP kann das WAFL Filesystem stilllegen, um ein absturzkonsistentes Backup zu machen.



== Cloud Volumes ONTAP unterstützt ausschließlich reservierte und On-Demand-VM-Instanzen

Cloud Volumes ONTAP kann auf einer reservierten oder On-Demand-VM-Instanz beim Cloud-Provider ausgeführt werden. Andere VM-Instanzen werden nicht unterstützt.



== Es sollten keine automatischen Lösungen für die Verwaltung von Anwendungsressourcen verwendet werden

Automatische Applikationsressourcenmanagement-Lösungen sollten die Cloud Volumes ONTAP-Systeme nicht verwalten. Dies kann zu einer Änderung an einer nicht unterstützten Konfiguration führen. Beispielsweise könnte mit der Lösung Cloud Volumes ONTAP zu einem nicht unterstützten VM-Instanztyp geändert werden.



== Software-Updates müssen über die NetApp Konsole durchgeführt werden

Upgrades von Cloud Volumes ONTAP müssen über die NetApp Konsole durchgeführt werden. Sie sollten Cloud Volumes ONTAP nicht mithilfe von System Manager oder der CLI aktualisieren. Dies kann die Systemstabilität beeinträchtigen.



== Die Cloud Volumes ONTAP-Bereitstellung darf nicht von der Konsole Ihres Cloud-Providers geändert werden

Änderungen an einer Cloud Volumes ONTAP -Konfiguration über die Konsole Ihres Cloud-Anbieters führen zu einer nicht unterstützten Konfiguration. Alle Änderungen an den Cloud Volumes ONTAP -Ressourcen, die die Konsole erstellt und verwaltet, können sich auf die Systemstabilität und die Fähigkeit der Konsole auswirken, das System zu verwalten.


NOTE: Nach der ersten Implementierung wird es unterstützt, den für Cloud Volumes ONTAP Ressourcen verwendeten Azure-Abonnementnamen zu ändern.



== Festplatten und Aggregate müssen über die Konsole verwaltet werden

Alle Datenträger und Aggregate müssen direkt von der Konsole aus erstellt und gelöscht werden. Sie sollten diese Aktionen nicht von einem anderen Verwaltungstool aus durchführen. Dies kann die Systemstabilität beeinträchtigen, die Möglichkeit, in Zukunft Festplatten hinzuzufügen, einschränken und möglicherweise zu überflüssigen Gebühren des Cloud-Anbieters führen.



== Einschränkung der SnapManager-Lizenzierung

SnapManager Lizenzen pro Server werden von Cloud Volumes ONTAP unterstützt. Lizenzen pro Storage-System (SnapManager Suite) werden nicht unterstützt.



== Einschränkungen bei Agenten und Nebenstellen von Drittanbietern

Agenten und VM-Erweiterungen von Drittanbietern werden auf Instanzen der virtuellen Cloud Volumes ONTAP-Maschinen nicht unterstützt.
