---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1 enthält eine neue Verbesserung. 
---
= Was ist neu in Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1 ist für die Bereitstellung und Aktualisierung in Azure und Google Cloud verfügbar.



== 9.17.1 RC1 (4. September 2025)

Sie können jetzt den Release Candidate 1 von Cloud Volumes ONTAP 9.17.1 für die Bereitstellung und Aktualisierung in Azure und Google Cloud verwenden. Diese Version ist jedoch nicht für die Bereitstellung und Aktualisierung in AWS verfügbar.



== Upgrade-Hinweise

Lesen Sie diese Hinweise, um mehr über das Upgrade auf diese Version zu erfahren.



=== Upgrade-Tipps

Upgrades von Cloud Volumes ONTAP müssen von BlueXP abgeschlossen werden. Sie sollten kein Cloud Volumes ONTAP-Upgrade mit System Manager oder der CLI durchführen. Dies kann die Stabilität des Systems beeinträchtigen.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie aktualisiert werden können, wenn Sie von BlueXP benachrichtigt werden"^].



=== Unterstützter Upgrade-Pfad

Sie können von der Version 9.16.1 in Azure und Google Cloud auf Cloud Volumes ONTAP 9.17.1 RC1 aktualisieren.  BlueXP fordert Sie auf, berechtigte Cloud Volumes ONTAP Systeme auf diese Version zu aktualisieren.


NOTE: Bei AWS werden Sie nicht zu diesem Upgrade aufgefordert.  Ein Upgrade auf Cloud Volumes ONTAP 9.17.1 RC1 wird in AWS nicht unterstützt.



=== Ausfallzeit

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars ist unterbrechungsfrei und die I/O-Vorgänge werden unterbrechungsfrei durchgeführt. Bei diesem unterbrechungsfreien Upgrade-Prozess wird jeder Node parallel aktualisiert, um weiterhin I/O für Clients zu ermöglichen.

