---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.19.1 enthält eine neue Verbesserung. 
---
= Was ist neu in Cloud Volumes ONTAP 9.19.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.19.1 kann jetzt bereitgestellt und aktualisiert werden. In der Konsole sind die Basisversion dieser Version sowie die neuesten Patch-Versionen verfügbar, die für Bereitstellung und Upgrade zur Verfügung stehen.

Weitere Informationen zu Cloud Volumes ONTAP Funktionen, unterstützten Konfigurationen, Limits und mehr sind unter  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP Dokumentation"^] zu finden.



[[9-19-1-10-august-2026]]
== 9.19.1 (10. August 2026)

Die Cloud Volumes ONTAP 9.19.1 General Availability (GA) Version ist jetzt ausschließlich in Amazon Web Services (AWS) und Google Cloud für die Bereitstellung und das Upgrade verfügbar. Diese Version ist nicht für die Bereitstellung und das Upgrade in Microsoft Azure (Azure) verfügbar.



[[upgrade-notes]]
== Upgrade-Hinweise

Lesen Sie diese Hinweise, um mehr über das Upgrade auf diese Version zu erfahren.



[[how-to-upgrade]]
=== Upgrade-Tipps

Upgrades von Cloud Volumes ONTAP müssen über die Konsole durchgeführt werden. Sie sollten Cloud Volumes ONTAP nicht mithilfe von System Manager oder der CLI aktualisieren. Dies kann die Systemstabilität beeinträchtigen.

https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie ein Upgrade durchführen, wenn die Konsole Sie benachrichtigt"^].



[[supported-upgrade-path]]
=== Unterstützter Upgrade-Pfad

Sie können in AWS und Google Cloud ein Upgrade von Cloud Volumes ONTAP 9.18.1 auf 9.19.1 durchführen. Die Konsole weist darauf hin, berechtigte Cloud Volumes ONTAP Systeme auf diese Version zu aktualisieren.


NOTE: In Azure werden Sie nicht zum Upgrade auf Version 9.19.1 aufgefordert, da diese Version bei diesem Cloud-Anbieter nicht für die Bereitstellung und das Upgrade verfügbar ist.



[[downtime]]
=== Ausfallzeit

* Das Upgrade eines Einzelknotensystems nimmt das System für bis zu 25 Minuten offline, währenddessen werden die I/O-Vorgänge unterbrochen.
* Das Upgrade eines HA-Paars ist unterbrechungsfrei und die I/O-Vorgänge werden unterbrechungsfrei durchgeführt. Bei diesem unterbrechungsfreien Upgrade-Prozess wird jeder Node parallel aktualisiert, um weiterhin I/O für Clients zu ermöglichen.

