---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.19.1 enthält eine neue Verbesserung. 
---
= Was ist neu in Cloud Volumes ONTAP 9.19.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.19.1 kann jetzt bereitgestellt und aktualisiert werden. In der Konsole sind die Basisversion dieser Version sowie die neuesten Patch-Versionen verfügbar, die für Bereitstellung und Upgrade zur Verfügung stehen.

Informationen zu den Cloud Volumes ONTAP-Funktionen, die in den neuesten Versionen der NetApp Console eingeführt wurden, finden Sie unter Neuerungen in https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^].



[[9-19-1-rc-13-july-2026]]
== 9.19.1 RC (13. Juli 2026)

Der Cloud Volumes ONTAP 9.19.1 Release Candidate (RC) ist jetzt ausschließlich für die Bereitstellung und das Upgrade in Google Cloud verfügbar. Diese Version ist für die Bereitstellung und das Upgrade in Amazon Web Services (AWS) und Microsoft Azure (Azure) nicht verfügbar.



[[upgrade-notes]]
== Upgrade-Hinweise

Lesen Sie diese Hinweise, um mehr über das Upgrade auf diese Version zu erfahren.



[[how-to-upgrade]]
=== Upgrade-Tipps

Upgrades von Cloud Volumes ONTAP müssen über die Konsole durchgeführt werden. Sie sollten Cloud Volumes ONTAP nicht mithilfe von System Manager oder der CLI aktualisieren. Dies kann die Systemstabilität beeinträchtigen.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie ein Upgrade durchführen, wenn die Konsole Sie benachrichtigt"^] .



[[supported-upgrade-path]]
=== Unterstützter Upgrade-Pfad

Ein Upgrade auf Cloud Volumes ONTAP 9.19.1 RC von 9.18.1 ist nur in Google Cloud möglich. Die Konsole fordert Sie auf, berechtigte Cloud Volumes ONTAP Systeme auf diese Version zu aktualisieren.


NOTE: In AWS und Azure erfolgt keine Aufforderung zum Upgrade auf 9.19.1 RC, da diese Version für diese Cloud-Anbieter nicht für Bereitstellung und Upgrade verfügbar ist.



[[downtime]]
=== Ausfallzeit

* Das Upgrade eines Einzelknotensystems nimmt das System für bis zu 25 Minuten offline, währenddessen werden die I/O-Vorgänge unterbrochen.
* Das Upgrade eines HA-Paars ist unterbrechungsfrei und die I/O-Vorgänge werden unterbrechungsfrei durchgeführt. Bei diesem unterbrechungsfreien Upgrade-Prozess wird jeder Node parallel aktualisiert, um weiterhin I/O für Clients zu ermöglichen.

