---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.12.1 enthält eine neue Verbesserung. 
---
= Was ist neu in Cloud Volumes ONTAP 9.12.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.1 umfasst neue Verbesserungen.

Zusätzliche Funktionen und Verbesserungen sind auch in den neuesten Versionen von BlueXP (ehemals Cloud Manager) verfügbar. Siehe https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Versionshinweise zu BlueXP"^] Entsprechende Details.



== 9.12.1 RC1 (8. Dezember 2022)

Cloud Volumes ONTAP 9.12.1 Release Candidate 1 ist jetzt in AWS, Azure und Google Cloud verfügbar. Diese Version umfasst die folgenden neuen Funktionen und Verbesserungen.



=== Unterstützter Upgrade-Pfad

Sie können ein Upgrade von Version 9.12.0 und Version 9.11.1 auf Cloud Volumes ONTAP 9.12.1 durchführen. Unter BlueXP werden Sie aufgefordert, qualifizierte Cloud Volumes ONTAP-Systeme auf diese Version zu aktualisieren.



=== Erforderliche Version des Connectors

Der BlueXP-Connector muss Version 3.9.23 oder höher ausführen, um neue Cloud Volumes ONTAP 9.12.1-Systeme bereitzustellen und bestehende Systeme auf 9.12.1 zu aktualisieren.


TIP: Automatische Upgrades des Connectors sind standardmäßig aktiviert, sodass Sie die neueste Version verwenden sollten.



=== ONTAP S3 Lizenz in GCP

Eine ONTAP S3 Lizenz ist jetzt auf neuen und vorhandenen Cloud Volumes ONTAP Systemen mit Version 9.12.1 oder höher in der Google Cloud Platform enthalten.

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Lesen Sie, wie Sie S3-Objekt-Storage-Services in ONTAP konfigurieren und managen"^]



=== Unterstützung von NVMe-TCP in Cloud Volumes ONTAP

NVMe-TCP wird für Cloud-Provider unterstützt, wenn Sie Cloud Volumes ONTAP Version 9.12.1 oder höher verwenden. BlueXP bietet keine Managementfunktionen für NVMe-TCP.

Weitere Informationen zum Konfigurieren von NVMe über ONTAP finden Sie unter link:https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["Konfigurieren Sie eine Storage-VM für NVMe"^].



=== Azure HA in einer einzelnen Verfügbarkeitszone mit gemeinsam genutzten, gemanagten Festplatten

Sie können jetzt eine Cloud Volumes ONTAP HA-Konfiguration mit lokalem Microsoft Azure Storage (LRS) implementieren, der auf gemeinsam genutzten, gemanagten Festplatten ausgeführt wird. Durch lokalen redundanten Storage werden Daten dreimal in einem einzelnen Datacenter in derselben Region repliziert.

Weitere Informationen zur HA-Konfigurationsarchitektur und -Komponenten finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Hochverfügbarkeitspaare in Azure"^].

Wenn Sie ein neues HA-Paar in Azure in einer einzelnen Verfügbarkeitszone implementieren, verwenden Sie jetzt LRS-Festplatten, die gemeinsam genutzt werden, anstatt Page Blobs für Storage zu verwenden. Der Assistent für die Arbeitsumgebung ändert sich nicht. Sie müssen lediglich eine Single Availability Zone auswählen, um diese neue Konfiguration zu verwenden. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["Starten eines Cloud Volumes ONTAP HA-Paars in Azure"^].



=== Azure HA in mehreren Verfügbarkeitszonen mit gemeinsam genutzten Festplatten

Jetzt können Sie eine Cloud Volumes ONTAP HA-Konfiguration mit Azure verschiedene Verfügbarkeitszonen innerhalb einer Region implementieren. Die neue Konfiguration schützt vor Datacenter-Ausfällen und erhält die Applikationsverfügbarkeit durch den Einsatz von ZRS (Shared Managed Disks) mit Azure Zone-Redundant Storage (ZRS).

Weitere Informationen zur HA-Konfigurationsarchitektur und -Komponenten finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Hochverfügbarkeitspaare in Azure"^].

Informationen zur Verwendung dieser neuen Konfiguration finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["Starten eines Cloud Volumes ONTAP HA-Paars in Azure"^].



== c4-, m4- und r4-Instanzen werden nicht mehr unterstützt (28. Oktober 2022)

In AWS werden die Instanztypen c4, m4 und r4 EC2 nicht mehr mit Cloud Volumes ONTAP unterstützt. Wenn Sie bereits ein System besitzen, das auf einem Instanztyp c4, m4 oder r4 ausgeführt wird, müssen Sie in der instanzfamilie c5, m5 oder r5 auf einen Instanztyp wechseln.

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["Erfahren Sie, wie Sie den EC2 Instanztyp für Cloud Volumes ONTAP ändern"^].

Siehe link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp Support"^] Hier erhalten Sie weitere Informationen über das Ende der Verfügbarkeit und die Unterstützung dieser Instanztypen.
