---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.17.1 enthält eine neue Verbesserung. 
---
= Was ist neu in Cloud Volumes ONTAP 9.17.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.17.1 enthält neue Verbesserungen.

In den neuesten Versionen der NetApp Console werden auch neue Cloud Volumes ONTAP -Funktionen eingeführt. Weitere Informationen finden Sie unter „Neuigkeiten in https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^] in der Konsole verwaltet.



== 9.17.1 P3 (22. Dezember 2025)

Der Cloud Volumes ONTAP 9.17.1 P3 Patch ist jetzt für das Upgrade in AWS, Azure und Google Cloud verfügbar. Die Konsole fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P3["Sehen Sie sich die Liste der im P3-Patch behobenen Fehler an"^](Anmeldung auf der NetApp Support-Site erforderlich).



== 9.17.1 P2 (04. Dezember 2025)

Der Cloud Volumes ONTAP 9.17.1 P2 Patch ist jetzt für das Upgrade in AWS, Azure und Google Cloud verfügbar. Die Konsole fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P2["Sehen Sie sich die Liste der im P2-Patch behobenen Fehler an"^](Anmeldung auf der NetApp Support-Site erforderlich).



== 9.17.1 P1 (04. November 2025)

Der Cloud Volumes ONTAP 9.17.1 P1 Patch ist jetzt für die Bereitstellung und das Upgrade in AWS, Azure und Google Cloud verfügbar. Die Konsole fordert Sie auf, Ihre vorhandenen Systeme auf diese Patch-Version zu aktualisieren.

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.17.1P1["Sehen Sie sich die Liste der im P1-Patch behobenen Fehler an"^](Anmeldung auf der NetApp Support-Site erforderlich).



== 9.17.1 RC1 (4. September 2025)

Sie können jetzt den Release Candidate 1 von Cloud Volumes ONTAP 9.17.1 für die Bereitstellung und Aktualisierung in Azure und Google Cloud verwenden.


NOTE: Diese Version steht für die Bereitstellung und das Upgrade in AWS nicht zur Verfügung.



== Upgrade-Hinweise

Lesen Sie diese Hinweise, um mehr über das Upgrade auf diese Version zu erfahren.



=== Upgrade-Tipps

Upgrades von Cloud Volumes ONTAP müssen über die Konsole durchgeführt werden. Sie sollten Cloud Volumes ONTAP nicht mithilfe von System Manager oder der CLI aktualisieren. Dies kann die Systemstabilität beeinträchtigen.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie ein Upgrade durchführen, wenn die Konsole Sie benachrichtigt"^] .



=== Unterstützter Upgrade-Pfad

Sie können in AWS, Azure und Google Cloud von der Version 9.16.1 auf Cloud Volumes ONTAP 9.17.1 aktualisieren.  Für AWS können Sie auf Cloud Volumes ONTAP 9.17.1 P1 und höher aktualisieren.  Die Konsole fordert Sie auf, kompatible Cloud Volumes ONTAP -Systeme auf diese Version zu aktualisieren.



=== Ausfallzeit

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars ist unterbrechungsfrei und die I/O-Vorgänge werden unterbrechungsfrei durchgeführt. Bei diesem unterbrechungsfreien Upgrade-Prozess wird jeder Node parallel aktualisiert, um weiterhin I/O für Clients zu ermöglichen.

