---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache; limitations in HA deployment in MAZ, SAZ, multiple availability xone, single availability zone Azure CVO, PSSDv2, premium SSD v2 limitation in CVO, flash cache limitation in CVO 
summary: Diese bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. 
---
= Bekannte Einschränkungen für Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. Schauen Sie sich das auch einmal an link:reference-limitations.html["Einschränkungen für Cloud Volumes ONTAP bei allen Cloud-Providern"].



== Beschränkungen bei der Verwendung von Azure VM-Erweiterungen

Cloud Volumes ONTAP unterstützt keine Azure-VM-Erweiterungen (Virtual Machine), da diese die BlueXP Verwaltungsvorgänge beeinträchtigen.  Während der Bereitstellung verhindert BlueXP die Installation jeglicher Erweiterungen auf Ihren VMs.  Wenn auf Ihren vorhandenen Cloud Volumes ONTAP VMs bereits Erweiterungen installiert sind, wenden Sie sich an den Microsoft Azure-Support, um sie zu entfernen.  Anleitungen finden Sie im Knowledge Base-Artikel (KB). https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Can_Azure_VM_Management_Extensions_be_installed_into_Cloud_Volume_ONTAP["Können Azure VM Management Extensions in Cloud Volume ONTAP installiert werden?"^]

Ab dem 14. Juli 2025 sendet NetApp E-Mails und benachrichtigt Sie in BlueXP , wenn VM-Erweiterungen auf Ihren Cloud Volumes ONTAP -VMs erkannt werden.



== Einschränkungen für Premium SSD v2-Datenträger für HA-Konfigurationen

Für verwaltete SSD Premium v2-Datenträger gelten die folgenden Einschränkungen für Hochverfügbarkeitsbereitstellungen (HA) in Azure:

* Wird in HA-Bereitstellungen in nicht zonalen Regionen nicht unterstützt.
* Wird in HA-Bereitstellungen über mehrere Verfügbarkeitszonen hinweg nicht unterstützt.
* Wird nur in HA-Konfigurationen unterstützt, die innerhalb einzelner Verfügbarkeitszonen bereitgestellt werden.


Um Premium SSD v2 Managed Disks mit Cloud Volumes ONTAP HA-Konfigurationen zu verwenden, stellen Sie sicher, dass die folgenden Anforderungen erfüllt sind:

* Die Cloud Volumes ONTAP Version ist 9.15.1 oder höher.
* Die HA-Bereitstellung erfolgt in einer einzelnen Azure-Verfügbarkeitszone.
* Die ausgewählten Regionen und Zonen unterstützen Premium SSD v2 Managed Disks.  Informationen zu den unterstützten Regionen finden Sie im https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Microsoft Azure-Website: Verfügbare Produkte nach Region"^] .


Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#support-for-premium-ssd-v2-managed-disks-in-azure["Unterstützung für verwaltete SSD Premium v2-Datenträger in Azure"^] .



== Einschränkungen bei HA-Implementierungen in einzelnen Verfügbarkeitszonen

Ab Cloud Volumes ONTAP 9.15.1 können Sie VM-Instanzen (Virtual Machine) im HA-Modus in einzelnen Verfügbarkeitszonen (AZs) in Azure bereitstellen. Informationen zu den Kriterien, die diese Funktion unterstützen, finden Sie unter https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-in-azure["HA-Paare in einzelnen Verfügbarkeitszonen in Azure implementieren"^] .

Wenn die Cloud Volumes ONTAP-Version älter als 9.15.1 ist oder eine dieser Bedingungen nicht erfüllt ist, wird das vorherige Bereitstellungsmodell, das Verfügbarkeitsgruppen verwendet, wirksam. Dies gilt nur für HA-Konfigurationen.



== Einschränkungen für Flash Cache

Cloud Volumes ONTAP verwendet in einigen VM-Typen den lokalen NVMe Storage als „_Flash Cache_“. Beachten Sie diese Einschränkung:

* Das Aufwärmen des Caches nach einem Neustart wird nicht unterstützt.




== Einschränkungen bei HA-Bereitstellungen

HA-Paare werden in einigen Regionen nicht unterstützt.

https://bluexp.netapp.com/cloud-volumes-global-regions["Zeigen Sie die Liste der unterstützten Azure Regionen an"^].
