---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.18.1 enthält eine neue Verbesserung. 
---
= Was ist neu in Cloud Volumes ONTAP 9.18.1
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können jetzt Cloud Volumes ONTAP 9.18.1 bereitstellen und aktualisieren. Sie können die Basisversion dieser Version und die neuesten Patch-Versionen, die für die Bereitstellung und das Upgrade verfügbar sind, in der Console einsehen.

Informationen zu den Cloud Volumes ONTAP-Funktionen, die in den neuesten Versionen der NetApp Console eingeführt wurden, finden Sie unter Neuerungen in https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html["Cloud Volumes ONTAP"^].



== 9.18.1 GA (10. Februar 2026)

Die Cloud Volumes ONTAP 9.18.1 General Availability-Version ist jetzt für die Bereitstellung und das Upgrade in Amazon Web Services (AWS) und Microsoft Azure verfügbar. Diese Version ist nicht für die Bereitstellung und das Upgrade in Google Cloud verfügbar.



== Upgrade-Hinweise

Lesen Sie diese Hinweise, um mehr über das Upgrade auf diese Version zu erfahren.



=== Upgrade-Tipps

Upgrades von Cloud Volumes ONTAP müssen über die Konsole durchgeführt werden. Sie sollten Cloud Volumes ONTAP nicht mithilfe von System Manager oder der CLI aktualisieren. Dies kann die Systemstabilität beeinträchtigen.

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["Erfahren Sie, wie Sie ein Upgrade durchführen, wenn die Konsole Sie benachrichtigt"^] .



=== Unterstützter Upgrade-Pfad

Sie können auf Cloud Volumes ONTAP 9.18.1 von den 9.17.1 P1 und späteren Patches in AWS und Azure aktualisieren. Die Console wird Sie auffordern, berechtigte Cloud Volumes ONTAP Systeme auf diese Version zu aktualisieren.


NOTE: Cloud Volumes ONTAP 9.18.1 ist in Google Cloud nicht für ein Upgrade verfügbar.



=== Ausfallzeit

* Das Upgrade eines einzelnen Node-Systems nimmt das System für bis zu 25 Minuten offline, während dieser I/O-Unterbrechung erfolgt.
* Das Upgrade eines HA-Paars ist unterbrechungsfrei und die I/O-Vorgänge werden unterbrechungsfrei durchgeführt. Bei diesem unterbrechungsfreien Upgrade-Prozess wird jeder Node parallel aktualisiert, um weiterhin I/O für Clients zu ermöglichen.

