---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support, SMB CA in CVO 
summary: Auf dieser Seite wird beschrieben, wie NetApp mit Cloud-Providern zusammenarbeitet, um auftretende Probleme zu beheben. 
---
= Zusammenarbeit mit Cloud-Providern für Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie, wie NetApp mit Cloud-Providern zusammenarbeitet, um potenzielle Probleme zu beheben.



== Gemeinsame Support Best Practices

NetApp verpflichtet sich, den Lizenznehmer zu unterstützen, und unternimmt wirtschaftlich angemessene Anstrengungen, um technische Support-Fälle für Cloud Volumes ONTAP zu lösen, sofern der Lizenznehmer diese Angaben macht. NetApp und der jeweilige Cloud-Provider haben keine direkten Support-Verpflichtungen bezüglich der lizenzierten Software oder Infrastruktur des jeweils anderen Anbieters.

NetApp hat Tools implementiert, mit denen sich Kunden mit anwendbaren Cloud-Providern in Verbindung setzen lassen, um technische Probleme bei Kunden zu lösen, die sich aus der jeweiligen Cloud-Provider-Services ergeben können. Allerdings Ein nahtloser Support-Ablauf ist für Kunden die beste Möglichkeit, (i) einen aktuellen Support-Vertrag mit NetApp und dem zuständigen Cloud-Provider aufrecht zu erhalten und (ii) gemeinsame Eskalationsmeetings mit NetApp und dem zuständigen Cloud-Provider zu koordinieren, wenn technische Probleme auftreten und der Kunde Klarheit hat Produkte oder Dienstleistungen, die diese technischen Probleme verursachen.



== Azure-Wartungsereignisse

Microsoft plant und kündigt programmgesteuert Wartungsereignisse in seiner Infrastruktur der Azure Virtual Machine (VM) an, die sich möglicherweise auf Cloud Volumes ONTAP VMs auswirken. Diese Ereignisse werden 15 Minuten vor dem Wartungsfenster bekannt gegeben.

Für Cloud Volumes ONTAP HA-Paare (High Availability, Hochverfügbarkeit) wird eine spezielle Handhabung der Wartungsereignisse unterstützt. Um den Applikationszustand zu erhalten, führen wir eine präventive Übernahme durch, um die Stabilität zu priorisieren, da jeder Ausfall der Konnektivität von mehr als 15 Sekunden Failover-Funktionen deaktiviert.

Wenn das Wartungsfenster angekündigt wird, führt der Partner-Node des Zielknoten einen Takeover durch. Nach Abschluss der Wartung wird ein Giveback initiiert. Nach dem Giveback wird erwartet, dass das HA-Paar wieder in einen ordnungsgemäßen Zustand versetzt wird. Falls dieses Problem nicht auftritt, wenden Sie sich an den NetApp Support, um Hilfe zu erhalten. Beachten Sie, dass Wartungsereignisse jeweils auf eine der VMs in einem HA-Paar ausgerichtet sind und typischerweise beide Nodes innerhalb relativ kurzer Zeit geplant sind.

CIFS/SMB-Clients, die nicht kontinuierlich verfügbare CIFS-Freigaben von Cloud Volumes ONTAP verwenden, verlieren ihre Sitzung sowohl bei einer Übernahme als auch bei der Rückgabe des von der Sitzung verwendeten Aggregats an dessen Home-Knoten. Dies ist eine Einschränkung des CIFS/SMB-Protokolls. Sie können zugelassene Produkte von Drittanbietern verwenden, um Probleme durch Übernahme und Rückgabe zu vermeiden. Wenden Sie sich für weitere Unterstützung an den NetApp Support.


NOTE: https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_SMB_Continuous_Availability_CA_Shares["Ständig verfügbare SMB-Freigaben"^] für unterbrechungsfreie Vorgänge werden in Cloud Volumes ONTAP nicht unterstützt.
