---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP hat in Google Cloud Einschränkungen bei der Storage-Konfiguration, um einen zuverlässigen Betrieb zu gewährleisten. Konfigurieren Sie das System nicht mit den Maximalwerten, um eine optimale Performance zu erzielen. 
---
= Storage-Limits für Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP verfügt über Einschränkungen bei der Storage-Konfiguration, um einen zuverlässigen Betrieb zu gewährleisten. Konfigurieren Sie das System nicht mit den Maximalwerten, um eine optimale Performance zu erzielen.



== Maximale Systemkapazität nach Lizenz

Die maximale Systemkapazität eines Cloud Volumes ONTAP-Systems wird durch seine Lizenz bestimmt. Die maximale Systemkapazität umfasst festplattenbasierten Storage sowie Objekt-Storage für Daten-Tiering.

NetApp unterstützt keine Überschreitung der Systemkapazitätsgrenze. Wenn Sie das lizenzierte Kapazitätslimit erreichen, zeigt die NetApp Konsole eine Aktionsmeldung an und lässt das Hinzufügen zusätzlicher Festplatten nicht mehr zu.

Bei einigen Konfigurationen verhindern Festplattenbeschränkungen, dass Sie durch die Verwendung von Festplatten allein das Kapazitätslimit nicht erreichen. Sie können die Kapazitätsgrenze um erreichen https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["tiering inaktiver Daten in Objektspeicher"^]. Weitere Details finden Sie in den Festplattenlimits unten.

.Kapazitätslimit für kapazitätsbasierte Lizenzen
Mit der kapazitätsbasierten Lizenzierung unterstützt jedes Cloud Volumes ONTAP -System die Einstufung in den Objektspeicher.  Die gesamte abgestufte Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden.  Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, sollten Sie die https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best Practices für FabricPool"^] um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung der Tiering-Ebene sicherzustellen. Weitere Informationen finden Sie im  https://cloud.google.com/storage/docs/buckets["Google Cloud-Dokumentation"^] für weitere Informationen.

Kapazitätsgrenzen für andere Lizenztypen::


[cols="25,75"]
|===
| Lizenz | Maximale Systemkapazität (Festplatten + Objekt-Storage) 


| Freimium | 500 GB 


| PAYGO Explore | 2 TB (Daten-Tiering wird nicht mit Explore unterstützt) 


| PAYGO-Standard | 10 TB 


| PAYGO Premium | 368 TB 


| Node-basierte Lizenz | 2 PiB (erfordert mehrere Lizenzen) 
|===
.Gibt es bei einem HA-Paar das Limit für lizenzierte Kapazität pro Node oder für das gesamte HA-Paar?
Das Kapazitätslimit liegt für das gesamte HA-Paar. Er erfolgt nicht pro Node. Wenn Sie beispielsweise die Premium-Lizenz verwenden, können Sie bis zu 368 TB Kapazität zwischen beiden Nodes haben.

.Werden bei einem HA-Paar die gespiegelten Daten an das lizenzierte Kapazitätslimit gezählt?
Nein, das tut es nicht. Daten in einem HA-Paar werden synchron zwischen den Knoten gespiegelt, sodass die Daten im Falle eines Ausfalls in Google Cloud verfügbar sind. Wenn Sie beispielsweise eine 8-TB-Festplatte auf Knoten A kaufen, weist die Konsole auch eine 8-TB-Festplatte auf Knoten B zu, die für gespiegelte Daten verwendet wird. Obwohl eine Kapazität von 16 TB eingerichtet ist, werden nur 8 TB auf das Lizenzlimit angerechnet.



== Aggregatgrenzen

Cloud Volumes ONTAP gruppiert Festplatten der Google Cloud Platform in _Aggregate_. Aggregate stellen Storage auf Volumes zur Verfügung.

[cols="2*"]
|===
| Parameter | Grenze 


| Maximale Anzahl an Datenaggregaten ^1^  a| 
* 99 für Single Node
* 64 bei einem gesamten HA-Paar




| Maximale Aggregatgröße | 256 TB Rohkapazität ^2^ 


| Disks pro Aggregat | 1-6 ^3^ 


| Maximale Anzahl von RAID-Gruppen pro Aggregat | 1 
|===
Hinweise:

. Die maximale Anzahl von Datenaggregaten beinhaltet nicht das Root-Aggregat.
. Die Festplatten, aus denen das Aggregat besteht, bestimmen die Kapazitätsgrenze des Aggregats.  Diese Begrenzung umfasst nicht den Objektspeicher, der für die Datenschichtung verwendet wird.
. Alle Festplatten in einem Aggregat müssen dieselbe Größe haben.




== Grenzwerte für Festplatte und Tiering

Die folgende Tabelle zeigt die maximale Systemkapazität mit Festplatten allein, mit Festplatten und selten benötigten Daten-Tiering in den Objekt-Storage. Die Festplattenbeschränkungen gelten für Festplatten, die Benutzerdaten enthalten. Die Einschränkungen umfassen nicht die Boot-Festplatte, die Root-Festplatte oder den NVRAM.

[cols="60,40"]
|===
| Parameter | Grenze 


| Maximale Anzahl Festplatten  a| 
* 124 für Single Node-Systeme
* 123 pro Node für HA-Paare




| Maximale Festplattengröße | 64 TB 


| Maximale Systemkapazität mit Festplatten allein | 256 TB ^1^ 


| Maximale Systemkapazität mit Festplatten und kalten Daten-Tiering zu einem Google Cloud Storage Bucket | Abhängig von der Lizenz. Siehe oben stehende maximale Systemkapazität. 
|===
^1^ Diese Grenze wird durch Virtual Machine-Limits in Google Cloud Platform definiert.



== Grenzwerte für Storage-VMs

Bei einigen Konfigurationen können Sie zusätzliche Storage VMs (SVMs) für Cloud Volumes ONTAP erstellen.

Dies sind die getesteten Grenzen.  Das Konfigurieren weiterer Speicher-VMs wird nicht unterstützt.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["Erfahren Sie, wie Sie zusätzliche Storage VMs erstellen"^].

[cols="2*"]
|===
| Lizenztyp | Begrenzung von Storage-VMs 


| *Freemium*  a| 
24 Storage VMs insgesamt ^1^



| *Kapazitätsbasierte PAYGO oder BYOL* ^2^  a| 
24 Storage VMs insgesamt ^1^



| *Node-basiertes BYOL* ^3^  a| 
24 Storage VMs insgesamt ^1^



| *Node-basiertes PAYGO*  a| 
* 1 Storage-VM zur Bereitstellung von Daten
* 1 Storage VM für Disaster Recovery


|===
. Diese 24 Storage VMs können Daten bereitstellen oder für die Disaster Recovery (DR) konfiguriert werden.
. Bei der kapazitätsbasierten Lizenzierung fallen keine zusätzlichen Lizenzkosten für zusätzliche Storage-VMs an, es entstehen jedoch mindestens 4 tib Mindestgebühren pro Storage-VM. Wenn Sie beispielsweise zwei Storage-VMs erstellen und jeweils 2 tib bereitgestellte Kapazität haben, werden Sie insgesamt 8 tib berechnet.
. Für knotenbasiertes BYOL ist für jede zusätzliche _Datenbereitstellungs_-Speicher-VM über die erste Speicher-VM hinaus, die standardmäßig mit Cloud Volumes ONTAP geliefert wird, eine Zusatzlizenz erforderlich.  Wenden Sie sich an Ihr Account-Team, um eine Add-On-Lizenz für Storage-VMs zu erhalten.
+
Storage VMs, die Sie für die Disaster Recovery (DR) konfigurieren, erfordern keine zusätzliche Lizenz (sie sind kostenlos), werden aber an die Storage-VM-Grenze angerechnet. Wenn Sie beispielsweise 12 Daten-Serving-Storage VMs und 12 Storage VMs für Disaster Recovery konfiguriert haben, haben Sie das Limit erreicht und Sie können keine zusätzlichen Storage VMs erstellen.





== Logische Storage-Einschränkungen

[cols="22,22,56"]
|===
| Logischer Storage | Parameter | Grenze 


.2+| *Dateien* | Maximale Größe ^2^ | 128 TB 


| Maximale Anzahl pro Volume | Volumengröße abhängig, bis zu 2 Milliarden 


| *FlexClone Volumes* | Hierarchische Klontiefe ^12^ | 499 


.3+| *FlexVol Volumes* | Maximal pro Node | 500 


| Mindestgröße | 20 MB 


| Maximale Größe ^3^ | 300 tib 


| *Qtrees* | Maximale Anzahl pro FlexVol Volume | 4,995 


| *Snapshot Kopien* | Maximale Anzahl pro FlexVol Volume | 1,023 
|===
. Diese hierarchische Klontiefe ist die maximale Tiefe einer geschachtelten Hierarchie der FlexClone Volumes, die aus einem einzelnen FlexVol Volume erstellt werden kann.
. Ab ONTAP 9.12.1P2 ist das Limit bei 128 TB. In ONTAP 9.11.1 und früheren Versionen beträgt die Grenze 16 TB.
. Die Erstellung von FlexVol Volumes bis zu einer maximalen Größe von 300 tib wird mit den folgenden Tools und Mindestversionen unterstützt:
+
** System Manager und die ONTAP CLI ab Cloud Volumes ONTAP 9.12.1 P2 und 9.13.0 P2
** Beginnend mit Cloud Volumes ONTAP 9.13.1






== ISCSI-Storage-Einschränkungen

[cols="3*"]
|===
| ISCSI-Storage | Parameter | Grenze 


.4+| *LUNs* | Maximal pro Node | 1,024 


| Die maximale Anzahl der LUN-Zuordnungen | 1,024 


| Maximale Größe | 16 TB 


| Maximale Anzahl pro Volume | 512 


| *Igroups* | Maximal pro Node | 256 


.2+| *Initiatoren* | Maximal pro Node | 512 


| Die maximale Anzahl pro Initiatorgruppe | 128 


| *ISCSI-Sitzungen* | Maximal pro Node | 1,024 


.2+| *LIFs* | Maximal pro Port | 1 


| Maximal pro Portsatz | 32 


| *Portsätze* | Maximal pro Node | 256 
|===


== Cloud Volumes ONTAP HA-Paare unterstützen kein sofortiges Storage-Giveback

Nach dem Neubooten eines Node muss der Partner die Daten synchronisieren, bevor er den Storage zurückgeben kann. Die Zeit, die für die Neusynchronisierung der Daten benötigt wird, hängt von der Menge der Daten ab, die von Clients geschrieben wurden, während der Node während des Giveback ausfällt und die Datenschreibgeschwindigkeit vorliegt.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["Funktionsweise von Storage in einem Cloud Volumes ONTAP HA-Paar in Google Cloud"^].
