---
sidebar: sidebar 
permalink: reference-configs-azure.html 
keywords: vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, disks, sizes 
summary: In Azure werden mehrere Cloud Volumes ONTAP Konfigurationen unterstützt. 
---
= Unterstützte Konfigurationen für Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Azure werden mehrere Cloud Volumes ONTAP Konfigurationen unterstützt.



== Unterstützte Konfigurationen nach Lizenz

Cloud Volumes ONTAP ist in Azure als Single-Node-System und als HA-Paar Nodes für Fehlertoleranz und unterbrechungsfreien Betrieb verfügbar.

Ein Upgrade eines Single Node-Systems auf ein HA-Paar wird nicht unterstützt. Wenn Sie zwischen einem Single Node-System und einem HA-Paar wechseln möchten, müssen Sie ein neues System implementieren und Daten vom bestehenden System auf das neue System replizieren.

Cloud Volumes ONTAP kann auf einer reservierten oder On-Demand-VM-Instanz beim Cloud-Provider ausgeführt werden. Lösungen, die andere VM-Instanztypen nutzen, werden nicht unterstützt.

Die Spezifikationen der unterstützten Instanzen finden Sie im  https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/overview["Microsoft Azure-Dokumentation"^] .



=== Systeme mit einzelnen Nodes

Bei der Implementierung von Cloud Volumes ONTAP als Single-Node-System in Azure können Sie aus den folgenden kapazitätsbasierten oder Node-basierten Lizenzierungskonfigurationen wählen.

Cloud Volumes ONTAP kann auf einer reservierten oder On-Demand-VM-Instanz beim Cloud-Provider ausgeführt werden. Lösungen, die andere VM-Instanztypen nutzen, werden nicht unterstützt.

[role="tabbed-block"]
====
.Kapazitätsbasierte Lizenzen
--
[cols="h,d,d,d"]
|===
|  | Freimium | Optimiert ^5^ | Kapazitätsbasierte Lizenz (Essentials und Professional) 


| Maximale Systemkapazität (Festplatten + Objekt-Storage) | 500 gib  a| 
Mit der kapazitätsbasierten Lizenzierung unterstützt jedes Cloud Volumes ONTAP -System die Einstufung in den Objektspeicher.  Die gesamte abgestufte Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden.  Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, sollten Sie die https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best Practices für FabricPool"^] um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung der Tiering-Ebene sicherzustellen.



| Unterstützte Typen von virtuellen Maschinen  a| 
* DS4_v2^ 1 ^
* DS5_v2 ^1^
* DS13_v2^ 1 ^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3^ 1 ^
* E8s_v3^ 1 ^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4
* E8ds_v4
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8S_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^

 a| 
* DS4_v2^ 1 ^
* DS13_v2^ 1 ^
* E4s_v3^ 1 ^
* E8s_v3^ 1 ^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E4ds_v5
* E8ds_v5

 a| 
* DS4_v2^ 1 ^
* DS5_v2 ^1^
* DS13_v2^ 1 ^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3^ 1 ^
* E8s_v3^ 1 ^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8S_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^




| Unterstützte Festplattentypen ^4^ 3+| Standard-HDD-Managed-Disks, Standard-SSD-Managed-Disks, Premium-SSD-Managed-Disks und Premium-SSD v2-Managed-Disks. 
|===
Hinweise:

. ^1^ die Maschinenfamilien DS_v2 und Es_v3 stehen bei der Bereitstellung neuer Instanzen von Cloud Volumes ONTAP in Azure nicht mehr zur Auswahl auf BlueXP  zur Verfügung. Diese Familien werden nur in älteren, bestehenden Systemen beibehalten und unterstützt. Neue Implementierungen von Cloud Volumes ONTAP werden in Azure erst ab Version 9.12.1 unterstützt. Wir empfehlen, entweder auf Es_v4 oder eine andere Serie zu wechseln, die mit Cloud Volumes ONTAP 9.12.1 und höher kompatibel ist. Die Maschinen der Serien DS_v2 und Es_v3 werden jedoch für neue Bereitstellungen über die API verfügbar sein.
. ^2^ dieser VM-Typ enthält lokalen NVMe Storage, den Cloud Volumes ONTAP als _Flash Cache_ verwendet. Flash Cache beschleunigt den Zugriff auf Daten durch intelligente Cache-Speicherung von kürzlich gelesenen Anwenderdaten und NetApp Metadaten in Echtzeit. Es bringt Vorteile bei Random Read-intensiven Workloads, einschließlich Datenbanken, E-Mail und File Services. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Weitere Informationen ."^].
+
Die ONTAP-Mindestversion, die für die Konfiguration von Flash Cache auf Azure erforderlich ist, ist 9.13.1 GA.

. ^3^ Diese VM-Typen verwenden ein für VNVRAM, was eine https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["Ultra SSD"^] bessere Schreibleistung bietet.
+
Wenn Sie bei der Bereitstellung eines neuen Cloud Volumes ONTAP Systems einen dieser VM-Typen auswählen, können Sie nicht zu einem anderen VM-Typ wechseln, der _keinen Ultra SSD für VNVRAM verwendet. Zum Beispiel, Sie können nicht von E8ds_v4 zu E8s_v3 ändern, aber Sie können von E8ds_v4 zu E32ds_v4 wechseln, weil beide VM-Typen Ultra SSDs verwenden. Ähnlich verhält es sich, wenn Sie ein neues Cloud Volumes ONTAP System bereitstellen, können Sie den VM-Typ nicht zu einem VM-Typ ändern, der Premium SSD v2 Managed Disks nicht unterstützt. Weitere Informationen zu den unterstützten Konfigurationen für Premium SSD v2 Managed Disks finden Sie unter https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["HA-Konfiguration mit einer einzelnen Verfügbarkeitszone und gemeinsam genutzten gemanagten Festplatten"^].

+
Umgekehrt können Sie bei einer Implementierung von Cloud Volumes ONTAP auf einen VM-Typ nicht zu einem VM-Typ wechseln, der eine Ultra SSD für VNVRAM verwendet. Beispielsweise können Sie nicht von E8s_v3 zu E8ds_v4 ändern.

. ^4^ Informationen zu den unterstützten Datenträgertypen in Einzelknotenbereitstellungen finden Sie unter  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html#azure-single-node["Azure (Single Node)"^] . Eine hohe Schreibgeschwindigkeit wird bei allen Instanztypen unterstützt, wenn ein System mit einem einzelnen Node verwendet wird. Sie können während der Implementierung oder zu einem beliebigen Zeitpunkt nach der Implementierung eine hohe Schreibgeschwindigkeit von BlueXP  aktivieren. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Erfahren Sie mehr über die Auswahl einer Schreibgeschwindigkeit"^]. Bei Verwendung von SSDs ist die verbesserte Schreib-Performance aktiviert.
. ^5^ Ab dem 11. August 2025 ist die Lizenz „Cloud Volumes ONTAP Optimized“ veraltet und kann im Azure Marketplace für Pay-as-you-go-Abonnements (PAYGO) nicht mehr erworben oder verlängert werden. Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Ende der Verfügbarkeit optimierter Lizenzen"^] .


--
.Node-basierte Lizenzen
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO-Standard | PAYGO Premium | Node-basiertes BYOL 


| Maximale Systemkapazität (Festplatten + Objekt-Storage) | 2 tib ^5^ | 10 tib | 368 tib | 368 tib pro Lizenz 


| Unterstützte Typen von virtuellen Maschinen  a| 
* E4s_v3^ 1 ^
* E4ds_v4 ^3^
* E4ds_v5

 a| 
* DS4_v2^ 1 ^
* DS13_v2^ 1 ^
* E8s_v3^ 1 ^
* E8ds_v4 ^3^
* E8ds_v5
* L8S_v3 ^2^

 a| 
* DS5_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^

 a| 
* DS4_v2^ 1 ^
* DS5_v2 ^1^
* DS13_v2^ 1 ^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E4s_v3^ 1 ^
* E8s_v3^ 1 ^
* E32s_v3 ^1,3^
* E48s_v3 ^1,3^
* E64is_v3 ^1,3^
* E4ds_v4 ^3^
* E8ds_v4 ^3^
* E32ds_v4 ^3^
* E48ds_v4 ^3^
* E80ids_v4 ^3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^3^
* E32ds_v5 ^3^
* E48ds_v5 ^3^
* E64ds_v5 ^3^
* L8S_v3 ^2^
* L16s_v3 ^2^
* L32s_v3 ^2^
* L48s_v3 ^2^
* L64s_v3 ^2^




| Unterstützte Festplattentypen ^4^ 4+| Standard-HDD-verwaltete Festplatten, Standard-SSD-verwaltete Festplatten und Premium-SSD-verwaltete Festplatten 
|===
Hinweise:

. ^1^ die Maschinenfamilien DS_v2 und Es_v3 stehen bei der Bereitstellung neuer Instanzen von Cloud Volumes ONTAP in Azure nicht mehr zur Auswahl auf BlueXP  zur Verfügung. Diese Familien werden nur in älteren, bestehenden Systemen beibehalten und unterstützt. Neue Implementierungen von Cloud Volumes ONTAP werden in Azure erst ab Version 9.12.1 unterstützt. Wir empfehlen, entweder auf Es_v4 oder eine andere Serie zu wechseln, die mit Cloud Volumes ONTAP 9.12.1 und höher kompatibel ist. Die Maschinen der Serien DS_v2 und Es_v3 werden jedoch für neue Bereitstellungen über die API verfügbar sein.
. ^2^ dieser VM-Typ enthält lokalen NVMe Storage, den Cloud Volumes ONTAP als _Flash Cache_ verwendet. Flash Cache beschleunigt den Zugriff auf Daten durch intelligente Cache-Speicherung von kürzlich gelesenen Anwenderdaten und NetApp Metadaten in Echtzeit. Es bringt Vorteile bei Random Read-intensiven Workloads, einschließlich Datenbanken, E-Mail und File Services. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Weitere Informationen ."^].
. ^3^ Diese VM-Typen verwenden ein für VNVRAM, was eine https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["Ultra SSD"^] bessere Schreibleistung bietet.
+
Wenn Sie bei der Bereitstellung eines neuen Cloud Volumes ONTAP Systems einen dieser VM-Typen auswählen, können Sie nicht zu einem anderen VM-Typ wechseln, der _keinen Ultra SSD für VNVRAM verwendet. Zum Beispiel, Sie können nicht von E8ds_v4 zu E8s_v3 ändern, aber Sie können von E8ds_v4 zu E32ds_v4 wechseln, weil beide VM-Typen Ultra SSDs verwenden.

+
Umgekehrt können Sie bei einer Implementierung von Cloud Volumes ONTAP auf einen VM-Typ nicht zu einem VM-Typ wechseln, der eine Ultra SSD für VNVRAM verwendet. Beispielsweise können Sie nicht von E8s_v3 zu E8ds_v4 ändern.

. ^4^ hohe Schreibgeschwindigkeit wird bei Verwendung eines Systems mit einem einzigen Node bei allen Instanztypen unterstützt. Sie können während der Implementierung oder zu einem beliebigen Zeitpunkt nach der Implementierung eine hohe Schreibgeschwindigkeit von BlueXP  aktivieren. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Erfahren Sie mehr über die Auswahl einer Schreibgeschwindigkeit"^]. Bei Verwendung von SSDs ist die verbesserte Schreib-Performance aktiviert.
. ^5^Daten-Tiering auf Azure Blob Storage wird von PAYGO Explore nicht unterstützt.


--
====


=== HA-Paare

Sie können eine der folgenden Konfigurationen wählen, wenn Sie Cloud Volumes ONTAP als HA-Paar in Azure implementieren.



==== HA-Paare mit Seite Blob

Sie können die folgenden Konfigurationen für die bestehenden Cloud Volumes ONTAP HA-Page-Blob-Implementierungen in Azure nutzen.


NOTE: Azure-Seiten-Blobs werden für keine neue Implementierung unterstützt.

[role="tabbed-block"]
====
.Kapazitätsbasierte Lizenzen
--
[cols="h,d,d,d"]
|===
|  | Freimium | Optimiert ^4^ | Kapazitätsbasierte Lizenz (Essentials und Professional) 


| Maximale Systemkapazität (Festplatten + Objekt-Storage) | 500 gib  a| 
Mit der kapazitätsbasierten Lizenzierung unterstützt jedes Cloud Volumes ONTAP -System die Einstufung in den Objektspeicher.  Die gesamte abgestufte Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden.  Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, sollten Sie die https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best Practices für FabricPool"^] um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung der Tiering-Ebene sicherzustellen.



| Unterstützte Typen von virtuellen Maschinen  a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^

 a| 
* DS4_v2
* DS13_v2
* E8s_v3
* E8ds_v4 ^3^
* E8ds_v5

 a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^




| Unterstützte Festplattentypen 3+| Blobs der Seite 
|===
Hinweise:

. ^1^ Cloud Volumes ONTAP unterstützt bei diesen VM-Typen eine hohe Schreibgeschwindigkeit bei Verwendung eines HA-Paares. Sie können während der Implementierung oder zu einem beliebigen Zeitpunkt nach der Implementierung eine hohe Schreibgeschwindigkeit von BlueXP  aktivieren. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["Erfahren Sie mehr über die Auswahl einer Schreibgeschwindigkeit"^].
. ^2^ Diese VM wird nur empfohlen, wenn eine Azure-Wartungskontrolle erforderlich ist. Aufgrund der höheren Preise wird dies nicht für andere Anwendungsfälle empfohlen.
. ^3^ Diese VMs werden nur in Bereitstellungen von Cloud Volumes ONTAP 9.11.1 oder früher unterstützt. Mit diesen VM-Typen können Sie eine bestehende Page Blob-Implementierung von Cloud Volumes ONTAP 9.11.1 auf 9.12.1 upgraden. Sie können keine neuen Seiten-Blob-Bereitstellungen mit Cloud Volumes ONTAP 9.12.1 oder höher durchführen.
. ^4^ Ab dem 11. August 2025 ist die Lizenz „Cloud Volumes ONTAP Optimized“ veraltet und kann im Azure Marketplace für Pay-as-you-go-Abonnements (PAYGO) nicht mehr erworben oder verlängert werden. Weitere Informationen finden Sie unter  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Ende der Verfügbarkeit optimierter Lizenzen"^] .


--
.Node-basierte Lizenzen
--
[cols="h,d,d,d"]
|===
|  | PAYGO-Standard | PAYGO Premium | Node-basiertes BYOL 


| Maximale Systemkapazität (Festplatten + Objekt-Storage) | 10 tib | 368 tib | 368 tib pro Lizenz 


| Unterstützte Typen von virtuellen Maschinen  a| 
* DS4_v2
* DS13_v2
* E8s_v3
* E8ds_v4 ^3^
* E8ds_v5

 a| 
* DS5_v2 ^1^
* DS14_v2 ^1^
* DS15_v2 ^1^
* E48s_v3 ^1^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^

 a| 
* DS4_v2
* DS5_v2 ^1^
* DS13_v2
* DS14_v2 ^1^
* DS15_v2 ^1^
* E8s_v3
* E48s_v3 ^1^
* E8ds_v4 ^3^
* E32ds_v4 ^1,3^
* E48ds_v4 ^1,3^
* E80ids_v4 ^1,2,3^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^




| Unterstützte Datenträgertypen 3+| Blobs der Seite 
|===
Hinweise:

. ^1^ Cloud Volumes ONTAP unterstützt bei diesen VM-Typen eine hohe Schreibgeschwindigkeit bei Verwendung eines HA-Paares. Sie können während der Implementierung oder zu einem beliebigen Zeitpunkt nach der Implementierung eine hohe Schreibgeschwindigkeit von BlueXP  aktivieren. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-write-speed.html["Erfahren Sie mehr über die Auswahl einer Schreibgeschwindigkeit"^].
. ^2^ Diese VM wird nur empfohlen, wenn eine Azure-Wartungskontrolle erforderlich ist. Aufgrund der höheren Preise wird dies nicht für andere Anwendungsfälle empfohlen.
. ^3^ Diese VMs werden nur in Bereitstellungen von Cloud Volumes ONTAP 9.11.1 oder früher unterstützt. Mit diesen VM-Typen können Sie eine bestehende Page Blob-Implementierung von Cloud Volumes ONTAP 9.11.1 auf 9.12.1 upgraden. Sie können keine neuen Seiten-Blob-Bereitstellungen mit Cloud Volumes ONTAP 9.12.1 oder höher durchführen.


--
====


==== HA-Paare mit gemeinsam genutzten, gemanagten Festplatten

Sie können eine der folgenden Konfigurationen wählen, wenn Sie Cloud Volumes ONTAP als HA-Paar in Azure implementieren.

[role="tabbed-block"]
====
.Kapazitätsbasierte Lizenzen
--
[cols="h,d,d,d"]
|===
|  | Freimium | Optimiert ^7^ | Kapazitätsbasierte Lizenz (Essentials und Professional) 


| Maximale Systemkapazität (Festplatten + Objekt-Storage) | 500 gib  a| 
Mit der kapazitätsbasierten Lizenzierung unterstützt jedes Cloud Volumes ONTAP -System die Einstufung in den Objektspeicher.  Die gesamte abgestufte Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden.  Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, sollten Sie die https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best Practices für FabricPool"^] um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung der Tiering-Ebene sicherzustellen.



| Unterstützte Typen von virtuellen Maschinen  a| 
* E8ds_v4
* E32ds_v4^ 1 ^
* E48ds_v4^ 1 ^
* E80ids_v4 ^1,2^
* E8ds_v5 ^4^
* E20ds_v5 ^1,4^
* E32ds_v5 ^1,4^
* E48ds_v5 ^1,4^
* E64ds_v5 ^1,4^
* L8s_v3 ^1,3, 5^
* L16s_v3 ^1,3,5^
* L32s_v3 ^1,3,5^
* L48s_v3 ^1,3, 5^
* L64s_v3 ^1,3, 5^

 a| 
* E8ds_v4
* E8ds_v5 ^4^

 a| 
* E8ds_v4
* E32ds_v4^ 1 ^
* E48ds_v4^ 1 ^
* E80ids_v4 ^1,2^
* E8ds_v5 ^4^
* E20ds_v5 ^1,4^
* E32ds_v5 ^1,4^
* E48ds_v5 ^1,4^
* E64ds_v5 ^1,4^
* L8s_v3 ^1,3, 5^
* L16s_v3 ^1,3,5^
* L32s_v3 ^1,3,5^
* L48s_v3 ^1,3, 5^
* L64s_v3 ^1,3, 5^




| Unterstützte Festplattentypen ^6^ 3+| Verwaltete Premium-SSD-Datenträger oder verwaltete Premium-SSD v2-Datenträger. 
|===
Hinweise:

. ^1^ Cloud Volumes ONTAP unterstützt bei diesen VM-Typen eine hohe Schreibgeschwindigkeit bei Verwendung eines HA-Paares. Sie können während der Implementierung oder zu einem beliebigen Zeitpunkt nach der Implementierung eine hohe Schreibgeschwindigkeit von BlueXP  aktivieren. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Erfahren Sie mehr über die Auswahl einer Schreibgeschwindigkeit"^].
. ^2^ Diese VM wird nur empfohlen, wenn eine Azure-Wartungskontrolle erforderlich ist. Aufgrund der höheren Preise wird dies nicht für andere Anwendungsfälle empfohlen.
. ^3^ Die Unterstützung mehrerer Verfügbarkeitszonen beginnt ab ONTAP Version 9.13.1.
. ^4^ Die Unterstützung mehrerer Verfügbarkeitszonen beginnt ab ONTAP Version 9.14.1 RC1.
. ^5^ Dieser VM-Typ umfasst lokalen NVMe-Speicher, den Cloud Volumes ONTAP als _Flash Cache_ verwendet. Flash Cache beschleunigt den Zugriff auf Daten durch intelligente Cache-Speicherung von kürzlich gelesenen Anwenderdaten und NetApp Metadaten in Echtzeit. Es bringt Vorteile bei Random Read-intensiven Workloads, einschließlich Datenbanken, E-Mail und File Services. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Weitere Informationen ."^].
. ^6^ Informationen zu den internen Festplatten für Systemdaten für HA-Bereitstellungen in einzelnen und mehreren Verfügbarkeitszonen finden Sie unter https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-default-configs.html#azure-ha-pair["Azure (HA-Paar)"^] .
. ^7^ Ab dem 11. August 2025 ist die Lizenz „Cloud Volumes ONTAP Optimized“ veraltet und kann im Azure Marketplace für Pay-as-you-go-Abonnements (PAYGO) nicht mehr erworben oder verlängert werden. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#11-august-2025["Ende der Verfügbarkeit optimierter Lizenzen"^] .


--
.Node-basierte Lizenzen
--
[cols="h,d,d,d"]
|===
|  | PAYGO-Standard | PAYGO Premium | Node-basiertes BYOL 


| Maximale Systemkapazität (Festplatten + Objekt-Storage) | 10 tib | 368 tib | 368 tib pro Lizenz 


| Unterstützte Typen von virtuellen Maschinen  a| 
* E8ds_v4 ^4^
* E8ds_v5
* L8s_v3 ^4,5^

 a| 
* E32ds_v4 ^1,4^
* E48ds_v4 ^1,4^
* E80ids_v4 ^1,2,4^
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^
* L16s_v3 ^1,4,5^
* L32s_v3 ^1,4,5^
* L48s_v3 ^1,4, 5^
* L64s_v3 ^1,4, 5^

 a| 
* E8ds_v4 ^4^
* E32ds_v4 ^1,4^
* E48ds_v4 ^1,4^
* E80ids_v4 ^1,2,4^
* E4ds_v5
* E8ds_v5
* E20ds_v5 ^1^
* E32ds_v5 ^1^
* E48ds_v5 ^1^
* E64ds_v5 ^1^
* L16s_v3 ^1,4,5^
* L32s_v3 ^1,4,5^
* L48s_v3 ^1,4, 5^
* L64s_v3 ^1,4, 5^




| Unterstützte Festplattentypen 3+| Gemanagte Festplatten 
|===
Hinweise:

. ^1^ Cloud Volumes ONTAP unterstützt bei diesen VM-Typen eine hohe Schreibgeschwindigkeit bei Verwendung eines HA-Paares. Sie können während der Implementierung oder zu einem beliebigen Zeitpunkt nach der Implementierung eine hohe Schreibgeschwindigkeit von BlueXP  aktivieren. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Erfahren Sie mehr über die Auswahl einer Schreibgeschwindigkeit"^].
. ^2^ Diese VM wird nur empfohlen, wenn eine Azure-Wartungskontrolle erforderlich ist. Aufgrund der höheren Preise wird dies nicht für andere Anwendungsfälle empfohlen.
. ^3^ Diese VM-Typen werden nur für HA-Paare in einer einzelnen Verfügbarkeitszonenkonfiguration unterstützt, die auf gemeinsam genutzten verwalteten Datenträgern ausgeführt wird.
. ^4^ Diese VM-Typen werden für HA-Paare in Konfigurationen mit einer oder mehreren Verfügbarkeitszonen unterstützt, die auf gemeinsam genutzten verwalteten Datenträgern ausgeführt werden. Für VM-Typen LS_v3 beginnt die Unterstützung mehrerer Verfügbarkeitszonen von ONTAP Version 9.13.1. Für VM-Typen mit Eds_v5 beginnt die Unterstützung mehrerer Verfügbarkeitszonen ab ONTAP Version 9.14.1 RC1.
. ^5^ Dieser VM-Typ umfasst lokalen NVMe-Speicher, den Cloud Volumes ONTAP als _Flash Cache_ verwendet. Flash Cache beschleunigt den Zugriff auf Daten durch intelligente Cache-Speicherung von kürzlich gelesenen Anwenderdaten und NetApp Metadaten in Echtzeit. Es bringt Vorteile bei Random Read-intensiven Workloads, einschließlich Datenbanken, E-Mail und File Services. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Weitere Informationen ."^].


--
====


== Unterstützte Festplattengrößen

In Azure kann ein Aggregat bis zu 12 Festplatten enthalten, die vom gleichen Typ und derselben Größe sind.



=== Systeme mit einzelnen Nodes

Systeme mit einem Node verwenden Azure Managed Disks. Folgende Festplattengrößen werden unterstützt:

[cols="3*"]
|===
| Premium SSD | Standard-SSD | Standard-HDD 


 a| 
* 500 gib
* 1 tib
* 2 tib
* 4 tib
* 8 tib
* 16 tib
* 32 tib

 a| 
* 100 gib
* 500 gib
* 1 tib
* 2 tib
* 4 tib
* 8 tib
* 16 tib
* 32 tib

 a| 
* 100 gib
* 500 gib
* 1 tib
* 2 tib
* 4 tib
* 8 tib
* 16 tib
* 32 tib


|===


=== HA-Paare

HA-Paare verwenden von Azure gemanagte Festplatten. Der folgende Festplattentyp und -Größen werden unterstützt.

(Page Blobs werden mit HA-Paaren unterstützt, die vor der Version 9.12.1 implementiert wurden.)

*Premium SSD*

* 500 gib
* 1 tib
* 2 tib
* 4 tib
* 8 tib
* 16 tib (nur gemanagte Festplatten)
* 32 tib (nur gemanagte Festplatten)




== Unterstützte Regionen

Informationen zur Unterstützung von Azure-Regionen finden Sie unter https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes Regionen Weltweit"^].
