---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: Diese bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. 
---
= Bekannte Einschränkungen für Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Microsoft Azure. Schauen Sie sich das auch einmal an link:reference-limitations.html["Einschränkungen für Cloud Volumes ONTAP bei allen Cloud-Providern"].



== Beschränkungen bei der Verwendung von Azure VM-Erweiterungen

Cloud Volumes ONTAP unterstützt keine Azure-VM-Erweiterungen, da diese die BlueXP -Verwaltung beeinträchtigen. Während der Bereitstellung verhindert BlueXP die Installation von Erweiterungen auf Ihren VMs. Sollten auf Ihren vorhandenen Cloud Volumes ONTAP VMs bereits Erweiterungen installiert sein, empfiehlt NetApp dringend, sich an den Microsoft Azure-Support zu wenden, um diese zu entfernen.

Ab dem 14. Juli 2025 benachrichtigt Sie NetApp in BlueXP und sendet E-Mails, wenn VM-Erweiterungen auf Ihren Cloud Volumes ONTAP -VMs erkannt werden.



== Einschränkungen für Flash Cache

Cloud Volumes ONTAP verwendet in einigen VM-Typen den lokalen NVMe Storage als „_Flash Cache_“. Beachten Sie diese Einschränkung:

* Das Aufwärmen des Caches nach einem Neustart wird nicht unterstützt.




== Einschränkungen bei Implementierungen mit hoher Verfügbarkeit

Hochverfügbarkeitspaare (HA) werden in einigen Regionen nicht unterstützt.

https://bluexp.netapp.com/cloud-volumes-global-regions["Zeigen Sie die Liste der unterstützten Azure Regionen an"^].



== Einschränkungen bei HA-Implementierungen in einzelnen Verfügbarkeitszonen

Ab Cloud Volumes ONTAP 9.15.1 können Instanzen von Virtual Machines (VM) im HA-Modus in einzelnen Verfügbarkeitszonen (AZS) in Azure implementiert werden. Informationen zu den Kriterien, die diese Funktion unterstützen, finden Sie unter https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["HA-Paare in einzelnen Verfügbarkeitszonen in Azure implementieren"^].

Wenn die Cloud Volumes ONTAP-Version älter als 9.15.1 ist oder eine dieser Bedingungen nicht erfüllt ist, wird das vorherige Bereitstellungsmodell, das Verfügbarkeitsgruppen verwendet, wirksam. Dies gilt nur für HA-Konfigurationen.
