---
sidebar: sidebar 
permalink: reference-limitations-aws.html 
keywords: limitations, aws, amazon web services, flashe cache, alarms, cloudwatch, giveback, govcloud, c2s, aws outpost, outposts 
summary: Diese bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Amazon Web Services. 
---
= Bekannte Einschränkungen für Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die folgenden bekannten Einschränkungen betreffen Cloud Volumes ONTAP in Amazon Web Services. Schauen Sie sich das auch einmal an link:reference-limitations.html["Einschränkungen für Cloud Volumes ONTAP bei allen Cloud-Providern"].



== Einschränkungen von AWS Outpost

Wenn Sie über einen AWS Outpost verfügen, können Sie Cloud Volumes ONTAP in diesem Outpost bereitstellen, indem Sie während der Bereitstellung das Outpost VPC auswählen. Die Erfahrung ist die gleiche wie bei jedem anderen VPC, das sich in AWS befindet.  Beachten Sie, dass Sie zuerst einen Konsolenagenten in Ihrem AWS Outpost bereitstellen müssen.

Es bestehen einige Einschränkungen, die darauf hinweisen:

* Derzeit werden nur Cloud Volumes ONTAP Systeme mit einzelnen Nodes unterstützt
* Die EC2 Instanzen, die Sie mit Cloud Volumes ONTAP verwenden können, sind auf die in Ihrem Outpost verfügbaren EC2-Instanzen beschränkt
* Derzeit werden nur General Purpose SSDs (gp2) unterstützt




== Einschränkungen für Flash Cache

Die Instanztypen C5D und R5D umfassen lokalen NVMe-Storage, der von Cloud Volumes ONTAP als _Flash Cache_ verwendet wird. Beachten Sie die folgenden Einschränkungen:

* Die Komprimierung muss auf allen Volumes deaktiviert sein, um die Performance-Verbesserungen durch Flash Cache bis zu Cloud Volumes ONTAP 9.12.0 nutzen zu können. Wenn Sie auf Cloud Volumes ONTAP 9.12.1 implementieren oder ein Upgrade durchführen, müssen Sie die Komprimierung nicht deaktivieren.
+
Sie können beim Erstellen eines Volumes über die NetApp Konsole keine Speichereffizienz wählen oder ein Volume erstellen und dann http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Deaktivieren Sie die Datenkomprimierung über die CLI"^] .

* Cloud Volumes ONTAP unterstützt das Neustarten des Cache nicht, wenn ein Neustart nach einem Neustart erfolgen soll.




== Von Amazon CloudWatch gemeldete Fehlalarme

Cloud Volumes ONTAP gibt also keine CPUs frei, wenn er im Leerlauf ist, also https://aws.amazon.com/cloudwatch/["Amazon CloudWatch"^] Kann eine hohe CPU-Warnung für die EC2 Instanz melden, da sie eine Auslastung von 100 % aufweist. Sie können diesen Alarm ignorieren. Mit dem Befehl ONTAP Statistics wird die tatsächliche Nutzung der CPUs angezeigt.



== Cloud Volumes ONTAP HA-Paare unterstützen kein sofortiges Storage-Giveback

Nach dem Neubooten eines Node muss der Partner die Daten synchronisieren, bevor er den Storage zurückgeben kann. Die Zeit, die für die Neusynchronisierung der Daten benötigt wird, hängt von der Menge der Daten ab, die von Clients geschrieben wurden, während der Node während des Giveback ausfällt und die Datenschreibgeschwindigkeit vorliegt.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html["Erfahren Sie, wie Storage in einem Cloud Volumes ONTAP HA-Paar in AWS ausgeführt wird"^].
