---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: Cloud Volumes ONTAP verfügt über Einschränkungen bei der Storage-Konfiguration in Azure, um einen zuverlässigen Betrieb zu gewährleisten. Konfigurieren Sie das System nicht mit den Maximalwerten, um eine optimale Performance zu erzielen. 
---
= Storage-Grenzen für Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP verfügt über Einschränkungen bei der Storage-Konfiguration, um einen zuverlässigen Betrieb zu gewährleisten. Konfigurieren Sie das System nicht mit den Maximalwerten, um eine optimale Performance zu erzielen.



== Maximale Systemkapazität nach Lizenz

Die maximale Systemkapazität eines Cloud Volumes ONTAP-Systems wird durch seine Lizenz bestimmt. Die maximale Systemkapazität umfasst festplattenbasierten Storage sowie Objekt-Storage für Daten-Tiering.

NetApp unterstützt keine Überschreitung der Systemkapazitätsgrenze. Wenn Sie das lizenzierte Kapazitätslimit erreichen, zeigt die NetApp Konsole eine Aktionsmeldung an und verhindert, dass Sie weitere Festplatten hinzufügen.

.Kapazitätslimit für kapazitätsbasierte Lizenzen
Mit der kapazitätsbasierten Lizenzierung unterstützt jedes Cloud Volumes ONTAP -System die Einstufung in den Objektspeicher.  Die gesamte abgestufte Kapazität kann bis zum Bucket-Limit des Cloud-Anbieters skaliert werden.  Obwohl die Lizenz keine Kapazitätsbeschränkungen vorsieht, sollten Sie die https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Best Practices für FabricPool"^] um optimale Leistung, Zuverlässigkeit und Kosteneffizienz bei der Konfiguration und Verwaltung der Tiering-Ebene sicherzustellen.  Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Azure-Dokumentation für verwaltete Datenträger"^] Und https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Azure-Dokumentation für Blob Storage"^] .

Kapazitätsgrenzen für andere Lizenztypen::


[cols="25,75"]
|===
| Lizenz | Maximale Systemkapazität (Festplatten + Objekt-Storage) 


| Freimium | 500 gib 


| PAYGO Explore | 2 tib (Daten-Tiering wird nicht mit Explore unterstützt) 


| PAYGO-Standard | 10 tib 


| PAYGO Premium | 368 tib 


| Node-basierte Lizenz | 2 PiB (erfordert mehrere Lizenzen) 
|===
.Ist bei HA die Lizenzkapazitätsgrenze pro Node oder für das gesamte HA-Paar?
Das Kapazitätslimit liegt für das gesamte HA-Paar. Er erfolgt nicht pro Node. Wenn Sie beispielsweise die Premium-Lizenz verwenden, können Sie bis zu 368 tib Kapazität zwischen beiden Nodes haben.



== Aggregatgrenzen

Cloud Volumes ONTAP nutzt Azure Storage als Festplatten und gruppiert diese in _Aggregate_. Aggregate stellen Storage auf Volumes zur Verfügung.

[cols="2*"]
|===
| Parameter | Grenze 


| Maximale Anzahl an Aggregaten | Entspricht der Festplattengrenze 


| Maximale Aggregatgröße ^1^ | 384 tib Bruttokapazität für einzelnen Node ^2^ 352 tib Bruttokapazität für einzelnen Node mit PAYGO 96 tib Rohkapazität für HA-Paare mit Seite Blob 384 tib Bruttokapazität für HA-Paare mit gemanagten Festplatten 


| Disks pro Aggregat | 1-12 ^3^ 


| Maximale Anzahl von RAID-Gruppen pro Aggregat | 1 
|===
Hinweise:

. Die Kapazitätsgrenze für das Aggregat basiert auf den Festplatten, die das Aggregat umfassen. Die Obergrenze enthält keinen Objekt-Storage, der für Daten-Tiering verwendet wird.
. Bei Verwendung der Node-basierten Lizenzierung sind zwei BYOL-Lizenzen erforderlich, um 384 tib zu erreichen.
. Alle Festplatten in einem Aggregat müssen dieselbe Größe haben.




== Festplatten- und Tiering-Größen werden nach VM-Größe begrenzt

Kapazitätsgrenzen variieren je nach VM-Größe und Systemtyp (Einzelknoten oder HA-Paar).

Die folgenden Hinweise erläutern die Zahlen in den Tabellen:

* Die Festplattenbeschränkungen gelten für Festplatten, die Benutzerdaten enthalten.
+
Die Einschränkungen umfassen nicht die Root-Festplatte, die Core-Festplatte und VNVRAM.

* Sie können die maximale Systemkapazität sehen, wenn Sie nur Festplatten verwenden und wenn Sie Festplatten und Cold Data Tiering zum Objektspeicher verwenden.
* Single Node und HA-Systeme, die gemanagte Festplatten verwenden, dürfen maximal 32 tib pro Festplatte verwenden. Die Anzahl der unterstützten Festplatten variiert je nach VM-Größe.
* HA-Systeme, die Blobs auf Seite verwenden, haben maximal 8 tib pro Seite BLOB. Die Anzahl der unterstützten Festplatten variiert je nach VM-Größe.
* Die für Einzelknotensysteme mit bestimmten VM-Größen angegebene Festplattengrenze von 896 TiB ist das _getestete_ Limit.




=== Grenzen für verschiedene Bereitstellungsmodi der kapazitätsbasierten Lizenzierung

Die folgenden Festplattenlimits gelten für Cloud Volumes ONTAP -Systeme, die ein kapazitätsbasiertes Lizenzpaket verwenden. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Weitere Informationen zu Cloud Volumes ONTAP Lizenzoptionen"^] .


NOTE: Informationen zur maximalen Systemkapazität und den Kapazitätsgrenzen für Daten-Tiering für einzelne Knoten, HA-Paare in einer einzelnen Verfügbarkeitszone mit Seitenblobs und HA-Paare in einer einzelnen und mehreren Verfügbarkeitszonen mit gemeinsam genutzten verwalteten Datenträgern finden Sie unter<<cap-license-azure>> .



==== Single Node

[cols="14,20,31"]
|===
| Die VM-Größe | MAX Data-Festplatten pro Node | Maximale Systemkapazität mit Festplatten allein 


| DS4_v2 | 29 | 896 tib 


| DS5_v2 | 61 | 896 tib 


| DS13_v2 | 29 | 896 tib 


| DS14_v2 | 61 | 896 tib 


| DS15_v2 | 61 | 896 tib 


| E4s_v3 | 5 | 160 tib 


| E8s_v3 | 13 | 416 tib 


| E32s_v3 | 29 | 896 tib 


| E48s_v3 | 29 | 896 tib 


| E64is_v3 | 29 | 896 tib 


| E4ds_v4 | 5 | 160 tib 


| E8ds_v4 | 13 | 416 tib 


| E32ds_v4 | 29 | 896 tib 


| E48ds_v4 | 29 | 896 tib 


| E80ids_v4 | 61 | 896 tib 


| E4ds_v5 | 5 | 160 tib 


| E8ds_v5 | 13 | 416 tib 


| E20ds_v5 | 29 | 896 tib 


| E32ds_v5 | 29 | 896 tib 


| E48ds_v5 | 29 | 896 tib 


| E64ds_v5 | 29 | 896 tib 


| L8S_v3 | 12 | 384 tib 


| L16s_v3 | 28 | 896 tib 


| L32s_v3 | 28 | 896 tib 


| L48s_v3 | 28 | 896 tib 


| L64s_v3 | 28 | 896 tib 
|===


==== HA-Paare in einer einzelnen Verfügbarkeitszone mit Seite-Blobs

[cols="14,20,31"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar | Maximale Systemkapazität mit Festplatten allein 


| DS4_v2 | 29 | 232 tib 


| DS5_v2 | 61 | 488 tib 


| DS13_v2 | 29 | 232 tib 


| DS14_v2 | 61 | 488 tib 


| DS15_v2 | 61 | 488 tib 


| E8s_v3 | 13 | 104 tib 


| E48s_v3 | 29 | 232 tib 


| E8ds_v4 | 13 | 104 tib 


| E32ds_v4 | 29 | 232 tib 


| E48ds_v4 | 29 | 232 tib 


| E80ids_v4 | 61 | 488 tib 
|===


==== HA-Paare in einer einzelnen Verfügbarkeitszone mit gemeinsam genutzten, gemanagten Festplatten

[cols="14,20,31"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar | Maximale Systemkapazität mit Festplatten allein 


| E8ds_v4 | 12 | 384 tib 


| E32ds_v4 | 28 | 896 tib 


| E48ds_v4 | 28 | 896 tib 


| E80ids_v4 | 28 | 896 tib 


| E8ds_v5 | 12 | 384 tib 


| E20ds_v5 | 28 | 896 tib 


| E32ds_v5 | 28 | 896 tib 


| E48ds_v5 | 28 | 896 tib 


| E64ds_v5 | 28 | 896 tib 


| L16s_v3 | 28 | 896 tib 


| L32s_v3 | 28 | 896 tib 


| L48s_v3 | 28 | 896 tib 


| L64s_v3 | 28 | 896 tib 
|===


==== HA-Paare in mehreren Verfügbarkeitszonen mit gemeinsam genutzten, gemanagten Festplatten

[cols="14,20,31"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar | Maximale Systemkapazität mit Festplatten allein 


| E8ds_v4 | 12 | 384 tib 


| E32ds_v4 | 28 | 896 tib 


| E48ds_v4 | 28 | 896 tib 


| E80ids_v4 | 28 | 896 tib 


| E8ds_v5 | 12 | 384 tib 


| E20ds_v5 | 28 | 896 tib 


| E32ds_v5 | 28 | 896 tib 


| E48ds_v5 | 28 | 896 tib 


| E64ds_v5 | 28 | 896 tib 


| L16s_v3 | 28 | 896 tib 


| L32s_v3 | 28 | 896 tib 


| L48s_v3 | 28 | 896 tib 


| L64s_v3 | 28 | 896 tib 
|===


=== Beschränkungen für verschiedene Bereitstellungsmodi der knotenbasierten Lizenzierung

Die folgenden Festplattenlimits gelten für Cloud Volumes ONTAP Systeme, die eine knotenbasierte Lizenzierung verwenden.  Die knotenbasierte Lizenzierung ist das Modell der vorherigen Generation, mit dem Sie Cloud Volumes ONTAP pro Knoten lizenzieren können.  Für bestehende Kunden ist die knotenbasierte Lizenzierung weiterhin verfügbar.

Sie können mehrere knotenbasierte Lizenzen für ein Cloud Volumes ONTAP BYOL-Einzelknoten- oder HA-Paarsystem erwerben, um mehr als 368 TiB Kapazität zuzuweisen, bis zur maximal getesteten und unterstützten Systemkapazitätsgrenze von 2 PiB.  Beachten Sie, dass Festplattenlimits Sie daran hindern können, die Kapazitätsgrenze zu erreichen, wenn Sie nur Festplatten verwenden.  Sie können das Festplattenlimit überschreiten, indem Sie https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["tiering inaktiver Daten in Objektspeicher"^] . https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["Erfahren Sie, wie Sie Cloud Volumes ONTAP zusätzliche Systemlizenzen hinzufügen"^] .  Cloud Volumes ONTAP unterstützt bis zur maximal getesteten und unterstützten Systemkapazität von 2 PiB. Das Überschreiten der 2-PiB-Grenze führt zu einer nicht unterstützten Systemkonfiguration.



==== Single Node

Single Node bietet zwei Node-basierte Lizenzoptionen: PAYGO Premium und BYOL.

.Single Node mit PAYGO Premium
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Die VM-Größe | MAX Data-Festplatten pro Node | Maximale Systemkapazität mit Festplatten allein | Maximale Systemkapazität mit Festplatten und Daten-Tiering 


| DS5_v2 | 61 | 368 tib | 368 tib 


| DS14_v2 | 61 | 368 tib | 368 tib 


| DS15_v2 | 61 | 368 tib | 368 tib 


| E32s_v3 | 29 | 368 tib | 368 tib 


| E48s_v3 | 29 | 368 tib | 368 tib 


| E64is_v3 | 29 | 368 tib | 368 tib 


| E32ds_v4 | 29 | 368 tib | 368 tib 


| E48ds_v4 | 29 | 368 tib | 368 tib 


| E80ids_v4 | 61 | 368 tib | 368 tib 


| E20ds_v5 | 29 | 896 tib | 2 PiB 


| E32ds_v5 | 29 | 896 tib | 2 PiB 


| E48ds_v5 | 29 | 896 tib | 2 PiB 


| E64ds_v5 | 29 | 896 tib | 2 PiB 
|===
====
.Einzelner Node mit BYOL
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Die VM-Größe | MAX Data-Festplatten pro Node 2+| Maximale Systemkapazität mit einer Lizenz 2+| Maximale Systemkapazität mit mehreren Lizenzen 


2+|  | *Festplatten allein* | *Festplatten + Daten-Tiering* | *Festplatten allein* | *Festplatten + Daten-Tiering* 


| DS4_v2 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| DS5_v2 | 61 | 368 tib | 368 tib | 896 tib | 2 PiB 


| DS13_v2 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| DS14_v2 | 61 | 368 tib | 368 tib | 896 tib | 2 PiB 


| DS15_v2 | 61 | 368 tib | 368 tib | 896 tib | 2 PiB 


| L8S_v2 | 13 | 368 tib | 368 tib | 416 tib | 2 PiB 


| E4s_v3 | 5 | 160 tib | 368 tib | 160 tib | 2 PiB 


| E8s_v3 | 13 | 368 tib | 368 tib | 416 tib | 2 PiB 


| E32s_v3 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E48s_v3 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E64is_v3 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E4ds_v4 | 5 | 160 tib | 368 tib | 160 tib | 2 PiB 


| E8ds_v4 | 13 | 368 tib | 368 tib | 416 tib | 2 PiB 


| E32ds_v4 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E48ds_v4 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E80ids_v4 | 61 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E4ds_v5 | 5 | 160 tib | 368 tib | 160 tib | 2 PiB 


| E8ds_v5 | 13 | 368 tib | 368 tib | 416 tib | 2 PiB 


| E20ds_v5 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E32ds_v5 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E48ds_v5 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 


| E64ds_v5 | 29 | 368 tib | 368 tib | 896 tib | 2 PiB 
|===
====


==== HA-Paare

HA-Paare haben zwei Konfigurationstypen: Page Blob und mehrere Verfügbarkeitszonen. Jede Konfiguration verfügt über zwei Node-basierte Lizenzoptionen: PAYGO Premium und BYOL.

.PAYGO Premium: HA-Paare in einer einzelnen Verfügbarkeitszone mit Seiten-Blobs
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar | Maximale Systemkapazität mit Festplatten allein | Maximale Systemkapazität mit Festplatten und Daten-Tiering 


| DS5_v2 | 61 | 368 tib | 368 tib 


| DS14_v2 | 61 | 368 tib | 368 tib 


| DS15_v2 | 61 | 368 tib | 368 tib 


| E8s_v3 | 13 | 104 tib | 368 tib 


| E48s_v3 | 29 | 232 tib | 368 tib 


| E32ds_v4 | 29 | 232 tib | 368 tib 


| E48ds_v4 | 29 | 232 tib | 368 tib 


| E80ids_v4 | 61 | 368 tib | 368 tib 
|===
====
.PAYGO Premium: HA-Paare in einer Konfiguration mit mehreren Verfügbarkeitszonen und gemeinsam genutzten gemanagten Festplatten
[%collapsible]
====
[cols="14,20,31,33"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar | Maximale Systemkapazität mit Festplatten allein | Maximale Systemkapazität mit Festplatten und Daten-Tiering 


| E32ds_v4 | 28 | 368 tib | 368 tib 


| E48ds_v4 | 28 | 368 tib | 368 tib 


| E80ids_v4 | 28 | 368 tib | 368 tib 


| E20ds_v5 | 28 | 896 tib | 2 PiB 


| E32ds_v5 | 28 | 896 tib | 2 PiB 


| E48ds_v5 | 28 | 896 tib | 2 PiB 


| E64ds_v5 | 28 | 896 tib | 2 PiB 
|===
====
.Byol: HA-Paare in einer einzelnen Verfügbarkeitszone mit Seite-Blobs
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar 2+| Maximale Systemkapazität mit einer Lizenz 2+| Maximale Systemkapazität mit mehreren Lizenzen 


2+|  | *Festplatten allein* | *Festplatten + Daten-Tiering* | *Festplatten allein* | *Festplatten + Daten-Tiering* 


| DS4_v2 | 29 | 232 tib | 368 tib | 232 tib | 2 PiB 


| DS5_v2 | 61 | 368 tib | 368 tib | 488 tib | 2 PiB 


| DS13_v2 | 29 | 232 tib | 368 tib | 232 tib | 2 PiB 


| DS14_v2 | 61 | 368 tib | 368 tib | 488 tib | 2 PiB 


| DS15_v2 | 61 | 368 tib | 368 tib | 488 tib | 2 PiB 


| E8s_v3 | 13 | 104 tib | 368 tib | 104 tib | 2 PiB 


| E48s_v3 | 29 | 232 tib | 368 tib | 232 tib | 2 PiB 


| E8ds_v4 | 13 | 104 tib | 368 tib | 104 tib | 2 PiB 


| E32ds_v4 | 29 | 232 tib | 368 tib | 232 tib | 2 PiB 


| E48ds_v4 | 29 | 232 tib | 368 tib | 232 tib | 2 PiB 


| E80ids_v4 | 61 | 368 tib | 368 tib | 488 tib | 2 PiB 
|===
====
.Byol: HA-Paare in einer Konfiguration mit mehreren Verfügbarkeitszonen und gemeinsam genutzten, gemanagten Festplatten
[%collapsible]
====
[cols="10,18,18,18,18,18"]
|===
| Die VM-Größe | MAX Data-Festplatten für ein HA-Paar 2+| Maximale Systemkapazität mit einer Lizenz 2+| Maximale Systemkapazität mit mehreren Lizenzen 


2+|  | *Festplatten allein* | *Festplatten + Daten-Tiering* | *Festplatten allein* | *Festplatten + Daten-Tiering* 


| E8ds_v4 | 12 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E32ds_v4 | 28 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E48ds_v4 | 28 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E80ids_v4 | 28 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E8ds_v5 | 12 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E20ds_v5 | 28 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E32ds_v5 | 28 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E48ds_v5 | 28 | 368 tib | 368 tib | 368 tib | 2 PiB 


| E64ds_v5 | 28 | 368 tib | 368 tib | 368 tib | 2 PiB 
|===
====


== Grenzwerte für Storage-VMs

Bei einigen Konfigurationen können Sie zusätzliche Storage VMs (SVMs) für Cloud Volumes ONTAP erstellen.

Dies sind die getesteten Grenzen.  Das Einrichten weiterer Speicher-VMs wird nicht unterstützt.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-azure.html["Erfahren Sie, wie Sie zusätzliche Storage VMs erstellen"^].

[cols="2*"]
|===
| Lizenztyp | Begrenzung von Storage-VMs 


| *Freemium*  a| 
24 Storage VMs insgesamt ^1,2^



| *Kapazitätsbasierte PAYGO oder BYOL* ^3^  a| 
24 Storage VMs insgesamt ^1,2^



| *Node-basiertes BYOL* ^4^  a| 
24 Storage VMs insgesamt ^1,2^



| *Node-basiertes PAYGO*  a| 
* 1 Storage-VM zur Bereitstellung von Daten
* 1 Storage VM für Disaster Recovery


|===
. Diese 24 Storage VMs können Daten bereitstellen oder für die Disaster Recovery (DR) konfiguriert werden.
. Jede Storage-VM kann bis zu drei logische Schnittstellen aufweisen, bei denen zwei Daten-LIFs sind, und eine davon ist eine SVM-Management-LIF.
. Bei der kapazitätsbasierten Lizenzierung fallen keine zusätzlichen Lizenzkosten für zusätzliche Storage-VMs an, es entstehen jedoch mindestens 4 tib Mindestgebühren pro Storage-VM. Wenn Sie beispielsweise zwei Storage-VMs erstellen und jeweils 2 tib bereitgestellte Kapazität haben, werden Sie insgesamt 8 tib berechnet.
. Bei Node-basiertem BYOL ist eine Add-on-Lizenz für jede zusätzliche _datenServing_ Storage-VM jenseits der ersten Storage-VM erforderlich, die standardmäßig mit Cloud Volumes ONTAP geliefert wird. Wenden Sie sich an Ihr Account-Team, um eine Add-on-Lizenz für eine Storage-VM zu erhalten.
+
Für Storage-VMs zur Notfallwiederherstellung (DR) ist keine Zusatzlizenz erforderlich, sie werden jedoch auf das Storage-VM-Limit angerechnet.  Wenn Sie beispielsweise über 12 Datenbereitstellungs- und 12 DR-Speicher-VMs verfügen, haben Sie das Limit erreicht und können keine weiteren erstellen.





== Datei- und Volume-Einschränkungen

[cols="22,22,56"]
|===
| Logischer Storage | Parameter | Grenze 


.2+| *Dateien* | Maximale Größe ^2^ | 128 TB 


| Maximale Anzahl pro Volume | Volumengröße abhängig, bis zu 2 Milliarden 


| *FlexClone Volumes* | Hierarchische Klontiefe ^1^ | 499 


.3+| *FlexVol Volumes* | Maximal pro Node | 500 


| Mindestgröße | 20 MB 


| Maximale Größe ^3^ | 300 tib 


| *Qtrees* | Maximale Anzahl pro FlexVol Volume | 4,995 


| *Snapshot Kopien* | Maximale Anzahl pro FlexVol Volume | 1,023 
|===
. Diese hierarchische Klontiefe ist die maximale Tiefe einer geschachtelten Hierarchie der FlexClone Volumes, die aus einem einzelnen FlexVol Volume erstellt werden kann.
. Ab ONTAP 9.12.1P2 ist das Limit bei 128 TB. In ONTAP 9.11.1 und früheren Versionen beträgt die Grenze 16 TB.
. Die Erstellung von FlexVol Volumes bis zu einer maximalen Größe von 300 tib wird mit den folgenden Tools und Mindestversionen unterstützt:
+
** System Manager und die ONTAP CLI ab Cloud Volumes ONTAP 9.12.1 P2 und 9.13.0 P2
** Beginnend mit Cloud Volumes ONTAP 9.13.1






== ISCSI-Storage-Einschränkungen

[cols="3*"]
|===
| ISCSI-Storage | Parameter | Grenze 


.4+| *LUNs* | Maximal pro Node | 1,024 


| Die maximale Anzahl der LUN-Zuordnungen | 1,024 


| Maximale Größe | 16 tib 


| Maximale Anzahl pro Volume | 512 


| *Igroups* | Maximal pro Node | 256 


.2+| *Initiatoren* | Maximal pro Node | 512 


| Die maximale Anzahl pro Initiatorgruppe | 128 


| *ISCSI-Sitzungen* | Maximal pro Node | 1,024 


.2+| *LIFs* | Maximal pro Port | 32 


| Maximal pro Portsatz | 32 


| *Portsätze* | Maximal pro Node | 256 
|===